### ISSUE TITLE
Vendor CSS?

### ISSUE THREAD

**Issue by paulxtiseo** [iOliverNguyen/mithril-boilerplate#1]
Where does one drop vendor-provided CSS files? (I can see how, in gulpfile.js, we can add JS and asset files in var vendorFiles for eventual inclusion.)

For example, I can install selectize.js from bower, and I need to include the JS (vendor\selectize\dist\js\standalone\selectize.js) and the Bootstrap CSS file (vendor\selectize\dist\css\selectize.bootstrap3.css). The latter I am not sure on the appropriate way to do this in your skeleton.

**Comment by iOliverNguyen** [comment]
In my skeleton, you can include it in `src/less/vendor.less` by using `@import (less) <file-path>`. Since a well-written CSS file is a valid LESS file. This approach has many benefits. (1) You get a single  `main-xxxxx.css` after compiling that browsers happily download and cache. (2) If the library supports LESS, you can choose which part to import.

```
@import (less) "../../vendor/selectize/dist/css/selectize.bootstrap3.css";
or
@import "../../vendor/selectize/src/less/selectize.bootstrap3.less"
```

Another way you should consider is including it directly in `index.html` by using `<link>`. You must also include the file path in `vendorFiles.assets` so that gulp can copy it to `build/public/assets/vendor`.
