### ISSUE TITLE
Why main.jsx And app.jsx?

### ISSUE THREAD

**Issue by paulxtiseo** [iOliverNguyen/mithril-boilerplate#2]
Why have a main.jsx that requires app.jsx? Why not combine them into one file?

Secondarily, min-require does or does not do any asynchronous (lazy) loading? Is it a stripped-down RequireJS? IOW, what is the raison d'etre of min-require?

Thanks for your time. Enjoying discovering how you structured an SPA.

**Comment by iOliverNguyen** [comment]
Hi paulxtiseo.

First, it's up to you. I prefer to put a main.jsx that requires app.jsx because I want to setup some things before calling app.jsx. For example, I may write code like this:

```
If ( currentUser ) {
  require('init-some-library');
  require('app');
} else {
  require('login');
}
```

Second, min-require does not do any asynchronous loading. It's only a tiny module that allow you to `define('A')` then `require('A')` in another place. All modules must be served at once (In the boilerplate, I concat all javascript files to a single file). Nothing more. (Unlike Node, min-require _does not_ support circular dependency)

The boilerplate is intended to quickly build a prototype. I do not recommend using it for long term projects. For complex projects, I'm currently using React with Flux and Isomorphic. Hope that help.

**Comment by paulxtiseo** [comment]
Interesting.

BTW, what is the issue(s) with the boilerplate for long-term projects? I've
been looking at it for precisely that reason, using parts of it and making
modifications along the way...

On Thu, Jan 15, 2015 at 8:31 PM, Vu Nguyen notifications@github.com wrote:

> Hi paulxtiseo.
> 
> First, it's up to you. I prefer to put a main.jsx that require app.jsx
> because I want to setup some things before calling app.jsx. For example, I
> may write code like this:
> 
> If ( currentUser ) {
>   require('init-some-library');
>   require('app');
> } else {
>   require('login');
> }
> 
> Second, min-require does not do any asynchronous loading. It's only a tiny
> module that allow you to define('A') then require('A') in another place.
> All modules must be served at once (In the boilerplate, I concat all
> javascript files to a single file). Nothing more.
> 
> The boilerplate is intended to quickly build a prototype. I do not
> recommend using it for long term projects. For complex projects, I
> currently using React with Flux and Isomorphic. Hope that help.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ng-vu/mithril-boilerplate/issues/2#issuecomment-70195066
> .

## 

---

_Paul Tiseo_
paulxtiseo@gmail.com
